title = "API Config"
documentation = "https://github.com/nmezhenskyi/gastronomy-api"

[environment]
host = "localhost"
port = "5000"
secure = false

[client]
url = "http://localhost:3000"

[database]
type = "postgres"
host = "localhost"
port = "5432"
database-name = "gastronomy"
username = "pg-user"
password = "pg-user"

[typeorm]
entities = [ "dist/models/*.js" ]
migrations = [ "dist/migrations/*.js" ]

[secrets]
jwt-access-secret = "p7kxjCY598ZiYHM5mNtU4rXs1iftsoh_kHpn7ievzW_T6HBQSv1pS3OEyzK_QQSW9qE8oCAdzWR7doBMy5I2Dw"
jwt-refresh-secret = "kdZ_qwfk_iWdeC68ppHqGcmMqJsnD8WlDcy2XchLzcRXCTcAFOyQfpmbiubQxWfkFpf3wfgbigutG6bWSRc1Bw"
