# Config overrides for test mode:

[database]
type = "postgres"
host = "localhost"
port = "5432"
name = "gastronomy"
username = "pg-user"
password = "pg-user"

[typeorm]
entities = [ "src/models/*.ts" ]
migrations = [ "src/migrations/*.ts" ]
